sudo: false
addons:
  apt:
    packages:
    - libicu-dev
    - libmozjs185-dev
    - pkg-config
    - help2man
    - libcurl4-openssl-dev
    - shunit2
before_script: ./configure -c --disable-docs --disable-fauxton
script:
   - ./run-tests.sh
language: erlang
otp_release:
   - 18.0
   - 17.5
   - R16B03-1
git:
  depth: 10
cache: apt
